// lib/screens/reading_therapy/reading_therapy_screen.dart
import 'dart:async';
import 'package:dhyana/models/article_model.dart';
import 'package:dhyana/providers/article_provider.dart';
import 'package:dhyana/providers/auth_provider.dart';
import 'package:dhyana/providers/progress_provider.dart';
import 'package:dhyana/widgets/common/app_bar_widget.dart';
import 'package:dhyana/widgets/common/loading_widget.dart';
import 'package:dhyana/widgets/common/mini_music_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:dhyana/core/constants/app_colors.dart';
import 'package:dhyana/core/constants/app_text_styles.dart';

class ReadingTherapyScreen extends ConsumerStatefulWidget {
  const ReadingTherapyScreen({super.key});

  @override
  ConsumerState<ReadingTherapyScreen> createState() =>
      _ReadingTherapyScreenState();
}

class _ReadingTherapyScreenState extends ConsumerState<ReadingTherapyScreen> {
  final Stopwatch _stopwatch = Stopwatch();

  @override
  void dispose() {
    _stopwatch.stop();
    super.dispose();
  }

  void _startTimer() {
    _stopwatch.reset();
    _stopwatch.start();
  }

  void _stopAndLogTimer() {
    _stopwatch.stop();
    final userId = ref.read(authStateProvider).value?.uid;
    if (userId != null) {
      ref
          .read(progressNotifierProvider.notifier)
          .logReadingTime(userId, _stopwatch.elapsed.inSeconds);
    }
  }

  @override
  Widget build(BuildContext context) {
    final articlesAsync = ref.watch(articlesProvider);
    final mindfulMoment = ref.watch(mindfulMomentProvider);
    final isDarkMode = Theme.of(context).brightness == Brightness.dark;

    ref.listen<MindfulMoment>(mindfulMomentProvider, (previous, next) {
      if (next.state == MindfulMomentState.data) {
        _startTimer();
      }
    });

    return Scaffold(
      appBar: CustomAppBar(
        title: 'Reading Therapy',
        showBackButton: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.bookmark_border),
            tooltip: 'Saved Articles',
            onPressed: () => context.push('/saved-articles'),
          ),
        ],
      ),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: isDarkMode
                ? [AppColors.backgroundDark, const Color(0xFF2C2C2C)]
                : [AppColors.backgroundLight, const Color(0xFFF0F0F0)],
          ),
        ),
        child: Column(
          children: [
            Expanded(
              child: ListView(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                children: [
                  _buildMindfulMomentsSection(context, mindfulMoment),
                  articlesAsync.when(
                    data: (groupedArticles) {
                      if (groupedArticles.isEmpty) {
                        return const Center(
                            child: Text('No articles available.'));
                      }
                      final categories = groupedArticles.keys.toList();
                      return Column(
                        children: categories.map((category) {
                          return _buildArticleCategoryRow(
                              context, category, groupedArticles[category]!);
                        }).toList(),
                      );
                    },
                    loading: () =>
                    const SizedBox(height: 250, child: LoadingWidget()),
                    error: (e, st) => Center(child: Text('Error: $e')),
                  ),
                ],
              ),
            ),
            const MiniMusicPlayer(),
          ],
        ),
      ),
    );
  }

  Widget _buildMindfulMomentsSection(
      BuildContext context, MindfulMoment mindfulMoment) {
    final notifier = ref.read(mindfulMomentProvider.notifier);
    final categories = [
      'Affirmation',
      'Short Story',
      'Mindful Joke',
      'Today\'s Fact'
    ];

    return Card(
      margin: const EdgeInsets.all(16.0),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Mindful Moments', style: AppTextStyles.headlineSmall),
            const SizedBox(height: 8),
            const Text(
                'Tap a category for a quick dose of mindfulness generated by AI.'),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8.0,
              runSpacing: 8.0,
              children: categories.map((category) {
                return ActionChip(
                  label: Text(category),
                  onPressed: () => notifier.fetchMoment(category),
                  avatar: const Icon(Icons.auto_awesome, size: 16),
                );
              }).toList(),
            ),
            AnimatedSwitcher(
              duration: const Duration(milliseconds: 300),
              child: mindfulMoment.state != MindfulMomentState.initial
                  ? Padding(
                padding: const EdgeInsets.only(top: 16.0),
                child: Container(
                  key: ValueKey(mindfulMoment.state),
                  padding: const EdgeInsets.all(16.0),
                  decoration: BoxDecoration(
                      color: Theme.of(context)
                          .colorScheme
                          .primary
                          .withOpacity(0.05),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                          color: Theme.of(context)
                              .colorScheme
                              .primary
                              .withOpacity(0.1))),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: [
                          IconButton(
                            icon: const Icon(Icons.close, size: 20),
                            onPressed: () {
                              _stopAndLogTimer();
                              notifier.clearMoment();
                            },
                            tooltip: 'Close and log reading time',
                          )
                        ],
                      ),
                      if (mindfulMoment.state ==
                          MindfulMomentState.loading)
                        const LoadingWidget(),
                      if (mindfulMoment.state ==
                          MindfulMomentState.data ||
                          mindfulMoment.state == MindfulMomentState.error)
                        Text(mindfulMoment.content,
                            style: AppTextStyles.bodyLarge),
                    ],
                  ),
                ),
              )
                  : const SizedBox.shrink(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildArticleCategoryRow(BuildContext context, String categoryTitle,
      List<ArticleModel> articles) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(16.0, 24.0, 16.0, 12.0),
          child: Text(
            categoryTitle,
            style: AppTextStyles.headlineSmall,
          ),
        ),
        SizedBox(
          height: 280,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 12.0),
            itemCount: articles.length,
            itemBuilder: (context, index) {
              return SizedBox(
                width: 220,
                child: InkWell(
                  onTap: () =>
                      context.push('/article-detail/${articles[index].id}'),
                  child: Card(
                    elevation: 2,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        if (articles[index].imageUrl != null)
                          ClipRRect(
                            borderRadius: const BorderRadius.only(
                              topLeft: Radius.circular(12),
                              topRight: Radius.circular(12),
                            ),
                            child: Image.network(
                              articles[index].imageUrl!,
                              height: 150,
                              width: double.infinity,
                              fit: BoxFit.cover,
                            ),
                          ),
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Text(
                            articles[index].title,
                            style: Theme.of(context).textTheme.titleMedium,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}